package main

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cshaizhihao/OU-UI/internal/agentruntime"
	"github.com/cshaizhihao/OU-UI/internal/tasks"
	"github.com/cshaizhihao/OU-UI/internal/tuning"
)

type registerRequest struct {
	InstallID    string                  `json:"installId"`
	Name         string                  `json:"name"`
	Version      string                  `json:"version"`
	System       agentruntime.SystemInfo `json:"system"`
	Capabilities []string                `json:"capabilities"`
}

type registerResponse struct {
	AgentID    string `json:"agentId"`
	AgentToken string `json:"agentToken"`
	InstallID  string `json:"installId"`
}

type heartbeatRequest struct {
	Status    string                      `json:"status"`
	Metrics   agentruntime.RuntimeMetrics `json:"metrics"`
	LastError string                      `json:"lastError"`
}

type nextTaskResponse struct {
	Task *tasks.Task `json:"task"`
}

type agentState struct {
	InstallID  string `json:"installId"`
	AgentID    string `json:"agentId"`
	AgentToken string `json:"agentToken"`
}

func (s agentState) registered() bool {
	return s.AgentID != "" && s.AgentToken != ""
}

type taskUpdateRequest struct {
	Status  string         `json:"status"`
	Result  map[string]any `json:"result"`
	Logs    string         `json:"logs"`
	Attempt int            `json:"attempt"`
}

func main() {
	serverURL := flag.String("server", getenv("OUUI_SERVER_URL", ""), "OU-UI server base URL, for example https://panel.example.com/secure")
	joinToken := flag.String("token", getenv("OUUI_AGENT_JOIN_TOKEN", ""), "one-time join token generated by the panel")
	name := flag.String("name", getenv("OUUI_AGENT_NAME", ""), "agent display name")
	interval := flag.Duration("interval", 10*time.Second, "heartbeat interval")
	dataDir := flag.String("data-dir", getenv("OUUI_AGENT_DATA_DIR", "/var/lib/ou-ui-agent"), "agent data directory")
	flag.Parse()

	if *serverURL == "" {
		log.Fatal("server is required")
	}
	if err := os.MkdirAll(*dataDir, 0o700); err != nil {
		log.Fatalf("create data dir: %v", err)
	}

	agentName := *name
	if agentName == "" {
		hostname, _ := os.Hostname()
		agentName = hostname
	}

	baseURL := strings.TrimRight(*serverURL, "/")
	client := &http.Client{Timeout: 15 * time.Second}
	state, err := loadState(*dataDir)
	if err != nil {
		log.Printf("load state failed, a new identity will be created: %v", err)
	}
	if state.InstallID == "" {
		state.InstallID = "ins_" + randomHex(16)
	}
	if !state.registered() {
		if *joinToken == "" {
			log.Fatal("token is required for first registration")
		}
		state, err = enroll(client, baseURL, *joinToken, agentName, state, *dataDir)
		if err != nil {
			log.Fatalf("register agent: %v", err)
		}
	} else {
		log.Printf("reusing persisted agent identity %s", state.AgentID)
	}

	ticker := time.NewTicker(*interval)
	defer ticker.Stop()
	executor := tasks.NewExecutor(*dataDir)
	sampler := agentruntime.NewSamplerWithDataDir(*dataDir)

	for {
		metrics := sampler.Collect()
		if err := heartbeat(client, baseURL, state.AgentID, state.AgentToken, metrics, ""); err != nil {
			log.Printf("heartbeat failed: %v", err)
			if isUnauthorized(err) && *joinToken != "" {
				log.Printf("agent token was rejected; trying reenrollment")
				if nextState, enrollErr := enroll(client, baseURL, *joinToken, agentName, state, *dataDir); enrollErr != nil {
					log.Printf("reenrollment failed: %v", enrollErr)
				} else {
					state = nextState
				}
			}
		}
		if err := runNextTask(client, baseURL, state.AgentID, state.AgentToken, executor); err != nil {
			log.Printf("task loop failed: %v", err)
		}
		<-ticker.C
	}
}

func enroll(client *http.Client, serverURL, joinToken, agentName string, state agentState, dataDir string) (agentState, error) {
	reg, err := register(client, serverURL, joinToken, registerRequest{
		InstallID:    state.InstallID,
		Name:         agentName,
		Version:      "v0.6.0",
		System:       agentruntime.CollectSystemInfo(),
		Capabilities: []string{"monitoring", tasks.CapabilityTaskPolling, "noop", "runtime.status", tuning.CapabilityHostOptimize, "routing.apply", "xray.render", "xray.deploy", "xray.service", "hysteria2.render", "hysteria2.deploy", "hysteria2.service"},
	})
	if err != nil {
		return state, err
	}
	state.AgentID = reg.AgentID
	state.AgentToken = reg.AgentToken
	if reg.InstallID != "" {
		state.InstallID = reg.InstallID
	}
	if err := saveState(dataDir, state); err != nil {
		return state, err
	}
	log.Printf("registered as %s", state.AgentID)
	return state, nil
}

func register(client *http.Client, serverURL, joinToken string, payload registerRequest) (registerResponse, error) {
	var out registerResponse
	body, _ := json.Marshal(payload)
	req, err := http.NewRequest(http.MethodPost, serverURL+"/api/v1/agents/register", bytes.NewReader(body))
	if err != nil {
		return out, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+joinToken)

	resp, err := client.Do(req)
	if err != nil {
		return out, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return out, statusError{Code: resp.StatusCode, Status: resp.Status}
	}
	return out, json.NewDecoder(resp.Body).Decode(&out)
}

func heartbeat(client *http.Client, serverURL, agentID, agentToken string, metrics agentruntime.RuntimeMetrics, lastError string) error {
	body, _ := json.Marshal(heartbeatRequest{Status: "online", Metrics: metrics, LastError: lastError})
	req, err := http.NewRequest(http.MethodPost, serverURL+"/api/v1/agents/"+agentID+"/heartbeat", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+agentToken)

	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return statusError{Code: resp.StatusCode, Status: resp.Status}
	}
	return nil
}

func runNextTask(client *http.Client, serverURL, agentID, agentToken string, executor tasks.Executor) error {
	task, err := pollTask(client, serverURL, agentID, agentToken)
	if err != nil {
		return err
	}
	if task == nil {
		return nil
	}
	log.Printf("executing task %s (%s), attempt %d", task.ID, task.Type, task.Attempts)
	result := executor.Execute(*task)
	if err := updateTask(client, serverURL, agentID, agentToken, *task, result); err != nil {
		return err
	}
	log.Printf("task %s finished with status %s", task.ID, result.Status)
	return nil
}

func pollTask(client *http.Client, serverURL, agentID, agentToken string) (*tasks.Task, error) {
	req, err := http.NewRequest(http.MethodGet, serverURL+"/api/v1/agents/"+agentID+"/tasks/next", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+agentToken)
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return nil, statusError{Code: resp.StatusCode, Status: resp.Status}
	}
	var out nextTaskResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out.Task, nil
}

func updateTask(client *http.Client, serverURL, agentID, agentToken string, task tasks.Task, result tasks.Result) error {
	body, _ := json.Marshal(taskUpdateRequest{
		Status:  result.Status,
		Result:  result.Result,
		Logs:    result.Logs,
		Attempt: task.Attempts,
	})
	req, err := http.NewRequest(http.MethodPatch, serverURL+"/api/v1/agents/"+agentID+"/tasks/"+task.ID, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+agentToken)
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return statusError{Code: resp.StatusCode, Status: resp.Status}
	}
	return nil
}

func loadState(dataDir string) (agentState, error) {
	var state agentState
	content, err := os.ReadFile(statePath(dataDir))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return state, nil
		}
		return state, err
	}
	return state, json.Unmarshal(content, &state)
}

func saveState(dataDir string, state agentState) error {
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return err
	}
	content, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(statePath(dataDir), content, 0o600)
}

func statePath(dataDir string) string {
	return filepath.Join(dataDir, "agent-state.json")
}

type statusError struct {
	Code   int
	Status string
}

func (e statusError) Error() string {
	return "server returned " + e.Status
}

func isUnauthorized(err error) bool {
	var status statusError
	return errors.As(err, &status) && status.Code == http.StatusUnauthorized
}

func randomHex(n int) string {
	if n <= 0 {
		return ""
	}
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err == nil {
		return hex.EncodeToString(buf)
	}
	seed := sha256.Sum256([]byte(time.Now().UTC().Format(time.RFC3339Nano)))
	text := hex.EncodeToString(seed[:])
	for len(text) < n*2 {
		next := sha256.Sum256([]byte(text))
		text += hex.EncodeToString(next[:])
	}
	return text[:n*2]
}

func getenv(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}
