package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/cshaizhihao/OU-UI/internal/agentruntime"
	"github.com/cshaizhihao/OU-UI/internal/tasks"
)

type registerRequest struct {
	Name          string                    `json:"name"`
	Version       string                    `json:"version"`
	System        agentruntime.SystemInfo   `json:"system"`
	Capabilities  []string                  `json:"capabilities"`
}

type registerResponse struct {
	AgentID    string `json:"agentId"`
	AgentToken string `json:"agentToken"`
}

type heartbeatRequest struct {
	Status  string                      `json:"status"`
	Metrics agentruntime.RuntimeMetrics `json:"metrics"`
}

type nextTaskResponse struct {
	Task *tasks.Task `json:"task"`
}

func main() {
	serverURL := flag.String("server", getenv("OUUI_SERVER_URL", ""), "OU-UI server base URL, for example https://panel.example.com/secure")
	joinToken := flag.String("token", getenv("OUUI_AGENT_JOIN_TOKEN", ""), "one-time join token generated by the panel")
	name := flag.String("name", getenv("OUUI_AGENT_NAME", ""), "agent display name")
	interval := flag.Duration("interval", 10*time.Second, "heartbeat interval")
	dataDir := flag.String("data-dir", getenv("OUUI_AGENT_DATA_DIR", "/var/lib/ou-ui-agent"), "agent data directory")
	flag.Parse()

	if *serverURL == "" || *joinToken == "" {
		log.Fatal("server and token are required")
	}

	agentName := *name
	if agentName == "" {
		hostname, _ := os.Hostname()
		agentName = hostname
	}

	client := &http.Client{Timeout: 15 * time.Second}
	system := agentruntime.CollectSystemInfo()
	reg, err := register(client, strings.TrimRight(*serverURL, "/"), *joinToken, registerRequest{
		Name:         agentName,
		Version:      "v0.3.0",
		System:       system,
		Capabilities: []string{"monitoring", tasks.CapabilityTaskPolling, "noop", "runtime.status", "xray.render", "hysteria2.render"},
	})
	if err != nil {
		log.Fatalf("register agent: %v", err)
	}

	log.Printf("registered as %s", reg.AgentID)
	ticker := time.NewTicker(*interval)
	defer ticker.Stop()
	executor := tasks.NewExecutor(*dataDir)

	for {
		metrics := agentruntime.CollectRuntimeMetrics()
		if err := heartbeat(client, strings.TrimRight(*serverURL, "/"), reg.AgentID, reg.AgentToken, metrics); err != nil {
			log.Printf("heartbeat failed: %v", err)
		}
		if err := runNextTask(client, strings.TrimRight(*serverURL, "/"), reg.AgentID, reg.AgentToken, executor); err != nil {
			log.Printf("task loop failed: %v", err)
		}
		<-ticker.C
	}
}

func register(client *http.Client, serverURL, joinToken string, payload registerRequest) (registerResponse, error) {
	var out registerResponse
	body, _ := json.Marshal(payload)
	req, err := http.NewRequest(http.MethodPost, serverURL+"/api/v1/agents/register", bytes.NewReader(body))
	if err != nil {
		return out, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+joinToken)

	resp, err := client.Do(req)
	if err != nil {
		return out, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return out, fmt.Errorf("server returned %s", resp.Status)
	}
	return out, json.NewDecoder(resp.Body).Decode(&out)
}

func heartbeat(client *http.Client, serverURL, agentID, agentToken string, metrics agentruntime.RuntimeMetrics) error {
	body, _ := json.Marshal(heartbeatRequest{Status: "online", Metrics: metrics})
	req, err := http.NewRequest(http.MethodPost, serverURL+"/api/v1/agents/"+agentID+"/heartbeat", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+agentToken)

	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return fmt.Errorf("server returned %s", resp.Status)
	}
	return nil
}

func runNextTask(client *http.Client, serverURL, agentID, agentToken string, executor tasks.Executor) error {
	task, err := pollTask(client, serverURL, agentID, agentToken)
	if err != nil {
		return err
	}
	if task == nil {
		return nil
	}
	log.Printf("executing task %s (%s)", task.ID, task.Type)
	result := executor.Execute(*task)
	if err := updateTask(client, serverURL, agentID, agentToken, task.ID, result); err != nil {
		return err
	}
	log.Printf("task %s finished with status %s", task.ID, result.Status)
	return nil
}

func pollTask(client *http.Client, serverURL, agentID, agentToken string) (*tasks.Task, error) {
	req, err := http.NewRequest(http.MethodGet, serverURL+"/api/v1/agents/"+agentID+"/tasks/next", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+agentToken)
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return nil, fmt.Errorf("server returned %s", resp.Status)
	}
	var out nextTaskResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out.Task, nil
}

func updateTask(client *http.Client, serverURL, agentID, agentToken, taskID string, result tasks.Result) error {
	body, _ := json.Marshal(result)
	req, err := http.NewRequest(http.MethodPatch, serverURL+"/api/v1/agents/"+agentID+"/tasks/"+taskID, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+agentToken)
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return fmt.Errorf("server returned %s", resp.Status)
	}
	return nil
}

func getenv(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}
